### ISSUE TITLE
invalid async code

### ISSUE THREAD

**Issue by vitaly-t** [DJviolin/template-literals#1]
https://github.com/DJviolin/template-literals/blob/1c6b38a91a2d77d045a7fd04f0be8383dcc928da/src/bin/www.js#L64

you can't do such things outside of asynchronous block above, which then will randomly fail ;)

**Comment by DJviolin** [comment]
Do you mean that `process.exit()` shouldn't be there in the `catch` block inside that `async` function? When the exception thrown, it's stopping the server as it should. Or is this a bad practice?

**Comment by vitaly-t** [comment]
actually, you do not need to do that there. the process doesn't exit because of the database connection pool, which you can shut down with `pgp.end()`, and then the process will exit without delay ;)

**Comment by DJviolin** [comment]
I wrote a test for checking if the process is halted when a table not found in the database. As you said, my code didn't catched the errors in a loop, resulting executing anyway a hundred times. I rewrote the function, and this one catching immediately the missing table:

```js
'use strict';

// node --use-strict src/.ignore/test-pgp.js

// pg-promise
// https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md
const db = require('../db/pgp').db;
const pgp = require('../db/pgp').pgp;

function UserException(message) {
  this.message = message;
  this.name = 'UserException';
}

async function query(tablename) {
  await db.task(async (t) => {
    let exist = null;
    try {
      exist = await t.one('SELECT to_regclass($1) AS exist;', tablename, a => a && a.exist);
      if (exist === null) {
        console.log('Database missing');
        throw new UserException(`Table NOT exist: ${exist}`);
      }
      console.log(`Database exists: ${exist}`);
    } catch (error) {
      console.log(`PGP ERROR: ${error.message || error}`); // print error;
      pgp.end();
      process.on('exit', (code) => {
        console.log(`About to exit with code: ${code}`);
      });
      process.exitCode = 9;
      process.exit();
    }
    return exist;
  });
}

for (let i = 0; i < 100; i += 1) {
  query('foo');
  query('foo2');
}
```

Resulting the console output:

```bash
$ node --use-strict src/.ignore/test-pgp.js
11:47:59 connect(postgres@postgres)
11:47:59 task/start
11:47:59 task: SELECT to_regclass('foo') AS exist;
Database exists: foo
11:47:59 task/end; duration: .012, success: true
11:47:59 connect(postgres@postgres)
11:47:59 disconnect(postgres@postgres)
11:47:59 task/start
11:47:59 task: SELECT to_regclass('foo2') AS exist;
Database missing
PGP ERROR: Table NOT exist: null
About to exit with code: 9
```

Is there any possible errors in this script?

**Comment by vitaly-t** [comment]
there 2 problems there...

1. if you want to use `pgp.end`, the logic should be:

```js
operation
   .then()
   .catch()
   .finally(pgp.end)
```

2. Your query logic is broken there:
```js
exist = await t.one('SELECT to_regclass($1) AS exist;', tablename, a => !!a.exist);
      if (!exist) {
        console.log('Database missing');
        throw new UserException(`Table NOT exist: ${exist}`);
      }
```
you were misusing parameter conversion between method `one` and `oneOrNone`.

**Comment by DJviolin** [comment]
The `!!` before `a.exist` converting the output to boolean?

My final code, I hope it's ok:

```js
'use strict';

// node --use-strict src/.ignore/test-pgp.js

// pg-promise
// https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md
const db = require('../db/pgp').db;
const pgp = require('../db/pgp').pgp;

function UserException(message) {
  this.message = message;
  this.name = 'UserException';
}

async function query(tablename) {
  await db.task(async (t) => {
    let exist = null;
    try {
      exist = await t.one('SELECT to_regclass($1) AS exist;', tablename, a => !!a.exist);
      if (!exist) {
        console.log('Database missing');
        throw new UserException(`Table NOT exist: ${exist}`);
      }
      console.log(`Database exists: ${exist}`);
    } catch (error) {
      console.log(`PGP ERROR: ${error.message || error}`); // print error;
      process.on('exit', (code) => {
        console.log(`About to exit with code: ${code}`);
      });
      process.exitCode = 9;
      process.exit();
    }
    return exist;
  });
}

for (let i = 0; i < 100; i += 1) {
  query('foo');
  query('foo2');
}
```

I'm not attached to use `pgp.end()` at all, if the server halting after the first error, it's fine.

**Comment by vitaly-t** [comment]
your problem is then - it will not exit when no error has been thrown, as you do not do `process.exit()` in the end of the `try` section.

**Comment by DJviolin** [comment]
I want it to not exit, when not found any error. If no error found (so the table exists), it should continue the initialize the server in `/bin/www`.

My first purpose with this table existence checking is to implement my passport.js session store in postgres (right now I use the default memory store), because if I restart my server, I not want my users to logged out. So if the session store table not existing, then the server init process will be halted, otherwise continue. Maybe I create the table then, but probably I will implement your example from [here](https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md) and no need for throwing exception:

```js
return exist || await t.one( ... );
```

For the sake of one problem at a time, right now I throwing exception if the table not found.

**Comment by vitaly-t** [comment]
Then it should be fine. Also see [examples](https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md).

**Comment by DJviolin** [comment]
Thank You for your help!
